name: craftgirlsss
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: any
  intl: ^0.18.1
  supabase: ^1.11.6
  supabase_flutter: ^1.10.4
  shared_preferences: ^2.2.1
  skeletons: ^0.0.3
  rounded_loading_button: ^2.1.0
  font_awesome_flutter: any
  introduction_screen: any
  cupertino_icons: ^1.0.2
  bottom_navy_bar: ^6.0.0
  animated_text_kit: ^4.2.2
  jumping_dot: ^0.0.6
  video_player: ^2.7.2
  photo_view: ^0.14.0
  image_picker: ^1.0.4
  file_picker: ^5.3.1
  carousel_slider: ^4.2.1
  flutter_animate: ^4.2.0
  http: ^0.13.6
  animations: ^2.0.7
  url_launcher: any
  dots_indicator: any
  five_pointed_star: ^1.0.3
  flutter_rating_bar: ^4.0.1
  # flutter_chat_ui: ^0.0.2
  open_filex: ^4.3.4
  flutter_chat_types: ^3.6.2
  uuid: ^4.1.0
  google_maps_flutter: ^2.3.0
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  location: ^4.4.0
  permission_handler: ^10.2.0
  flutter_staggered_animations: ^1.1.1
  animated_button: ^0.2.0
  flutter_animated_button: ^2.0.3
  date_field: ^3.0.5
  badges: ^3.1.1
  # flutter_cupertino_date_picker: ^1.0.26+2
  # flutter_svg: ^2.0.5
  # rxdart: ^0.27.7
  # cached_network_image: ^3.2.3
  # qrscan: ^0.3.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/craftgirlsss.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/freshicons/

  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat.ttf
    #         style: italic
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf
